### ISSUE TITLE
Uncaught ReferenceError: goog is not defined

### ISSUE THREAD

**Issue by jimbojetlag** [mxmul/closure-loader#2]
I tried to follow README, but all I get is `Uncaught ReferenceError: goog is not defined`.

Here is my webpack config:

``` javascript
var path = require('path');
var webpack = require('webpack');

module.exports = {
  context: path.join(__dirname, '/src'),

  entry: {
    app: [
      'webpack-dev-server/client?http://localhost:8080/assets/',
      'webpack/hot/only-dev-server',
      './app.js'
    ]
  },

  output: {
    filename: '[name].js',
    path: path.join(__dirname, '/dist'),
    publicPath: '/assets/'
  },

  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['react-hot', 'babel-loader', 'closure-loader']
      },
      {
        test: /\.html$/,
        loader: "file?name=[name].[ext]"
      }
    ]
  },

  closureLoader: {
    paths: [
      path.join(__dirname, 'node_modules', 'google-closure-library', 'closure'),
      path.join(__dirname, '/src')
    ],
    es6mode: true
  }
}
```

**Comment by eXaminator** [comment]
Hi, I'll have a look at this tonight, but here is a quick guess:

The closure-loader **only** manages dependencies via `goog.provide` and `goog.require`.

If you want to use any other features from the closure library you'll have to require it somehow. You could try using the [expose-loader](https://github.com/webpack/expose-loader) to expose the global `goog` variable in every module.

**Comment by jimbojetlag** [comment]
Thanks. The error is for `goog.provide`

**Comment by eXaminator** [comment]
I think I know what your problem is. I wasn't able to get this 100% working with the whole closure lib yet though.

In your case you excluded the `node_modules` directory from the closure loader:

``` javascript
{
        test: /\.js$/,
        exclude: /node_modules/,
        loaders: ['react-hot', 'babel-loader', 'closure-loader']
}
```

That's probably why you get the error on `goog.provide`. Please either remove/change the exclude or add another loader for your `node_modules/google-closure-library` directory and see if that helps you. Please come back with further problems you encounter.

**Comment by jimbojetlag** [comment]
You're right. I tried to separate the loaders like this:

``` javascript
module: {
  loaders: [
    {
      test: /\.js$/,
      loaders: ['closure-loader']
    },
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loaders: ['react-hot', 'babel-loader']
    }
  ]
}
```

and now I get this error:

```
Unhandled rejection TypeError: Cannot read property 'goog.string.linkify' of undefined
    at createRequire (.../node_modules/closure-loader/index.js:99:20)
```

Looks like `provideMap` in that line is not defined.

**Comment by jimbojetlag** [comment]
Sorry, forgot to update the pattern, I set it to `node_modules/google-closure-library` as you instructed:

``` javascript
module: {
  loaders: [
    {
      test: /node_modules\/google-closure-library\/.*\.js$/,
      loaders: ['closure-loader']
    },
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loaders: ['react-hot', 'babel-loader']
    }
  ]
}
```

and now I'm back to the initial error of `goog is not defined`.

**Comment by eXaminator** [comment]
You need to use the closure-loader for all files that contain a `goog.require` or `goog.provide`.

So if you use one of those statements in your own project files (those that are loaded via the second loader definition), then you need to **also** add the closure-loader to that second definition like you had before.

The next problem will occur once you try to use other goog functions like `goog.inherits` or `goog.base`. The problem here is, that you would need to to access the global `goog` variable inside your modules. This is not in the scope of this loader though. I am currently looking into this though and maybe I'll be able to put together a small example application or two on how to use this loader in conjunction with the closure library, either with ES6 or without.

**Comment by jimbojetlag** [comment]
Thanks, I wait for your working examples.

**Comment by eXaminator** [comment]
I have created some examples, hopefully they help you getting your project running. I also found a bug that might have been the source of your problems and fixed that. I also found some other bugs (and created issues for them) and I will see to get them fixed at some point. But if you keep to the examples you should get this running. I'll close this issue for now, but please come back if you encounter any further problems.
