### ISSUE TITLE
Resolving only JS files - Not respecting configuration

### ISSUE THREAD

**Issue by petrleocompel** [mxmul/closure-loader#23]
Problem is this line - dependencyMapBuilder.js:64
```javascript
return glob(path.join(directory, '/**/*.js'));
```

You are resolving only JS files which is not correct, because you are not respecting configuraction.

My webpack loaders configuration
```javascript
{
    test: /\.jsx$/,
    exclude: [/node_modules/, /\/src\/lib\/.*/g],
    loaders: ['closure-loader', 'babel-loader']
},
{
    test: /\.js?$/,
    exclude: [/node_modules/,  /\/src\/lib\/.*/g],
    loaders: ['closure-loader']
}
```
So if file is JSX then i want it load by babel-loader and then by closure-loader.
If i override dependencyMapBuilder.js:64 to this than it is working ok.
```javascript
return glob(path.join(directory, '/**/*.js?(x)'));
```
But there should be something like this
```javascript
return glob(path.join(directory, '/**/' + convertedFileTestFromWebpackFromConfig));
```

Maybe i will try to make pull request.

**Comment by eXaminator** [comment]
Good point, but I have the feeling this might not be as simple (as there is no way of knowing if the regex is actually representing a file extension or anything like that...). Maybe I could expand the glob to return all files no matter the extension, but that could open up a whole lot of other problems.

As I see it this loader was created to support legacy code. New code should always use ES6 modules instead of `goog.require()` and `goog.provide()`. So if you actually have jsx files which contain `goog.provide()`calls I would highly recommend to change that if possible.

As for this issue, I will leave it open for now and see if I find some time to look at it in depth. But it might take a while.

**Comment by petrleocompel** [comment]
I understand. But let me explain my situation to you. 
App is writen in ES5 - goog. And from time to time we are writting new code to this app. And we would like to write it in ES6. And if you want to use ES6 and closure together you have to transpile ES6 to ES5 before closure-loader will receive it. 

Maybe it will be good to have some configuration to use custom file ext test. To determine which ext you want to load.

**Comment by eXaminator** [comment]
Closure compiler does understand some ES6 including modules as it seems: https://github.com/google/closure-compiler/wiki/ECMAScript6

Maybe look into that? Otherwise I would use es6 modules for your new code and simply import it within your old code using es6 import (if you also run your old code base through babel).

The only problem here is, that your jsx files contain `goog.provide` calls which I would - in your place - try to avoid at all costs (`goog.require`should work, even within jsx, if I'm not mistaken).

If all else fails: a configuration option might be a good quick and non-breaking fix to this. I would gladly take a PR for this if you would create one. :)

**Comment by petrleocompel** [comment]
I think the file ext should be configurable. Because you can name your file as `.es`,`.es6` and others. So I'm going to do pull request.

**Comment by petrleocompel** [comment]
Also if we provide configuration then you can use also with Coffee script (for example). 
Because you will be able to load Coffee script file with their loader and then send to closure-loader. 
I know it's :pig: thing for old legacy code is great.
