### ISSUE TITLE
Uncaught TypeError: goog.string.contains is not a function

### ISSUE THREAD

**Issue by ambar** [mxmul/closure-loader#8]
``` js
// legacy-closure-lib/src/app.js
goog.require('goog.ui.Component')

// or es6-closure-lib/src/app.js
import Component from 'google-closure-library/closure/goog/ui/Component'
```

**Comment by eXaminator** [comment]
Thanks for reporting this. I'll take a look at this as soon as I can (but probably not today).

**Comment by eXaminator** [comment]
I just release a new version. 
1. I fixed a bug that was causing the above error message.
2. I encountered some further problems which was due to bad shimming of `base.js` in the examples. So please look at those and update your webpack configuration appropriately.

If you encounter any more problems let me know!
